"""Interface-neutral application operations for user-visible workflows.

Owns orchestration that is shared across CLI and MCP surfaces.
Does not own durable persistence primitives or transport-specific handling.

Usage:
    from brain_sync.application import add_source, list_sources
    sources = list_sources()  # auto-discovers the active brain root from config
"""

from brain_sync.application.browse import (
    ALLOWED_EXTENSIONS,
    DEFAULT_FILE_CHARS,
    MAX_AREAS_LISTED,
    MAX_CHILDREN,
    MAX_FILE_CHARS,
    MAX_SUMMARY_CHARS,
    TRUNCATION_MARKER,
    AreaChild,
    AreaListing,
    AreaNotFoundError,
    BrainContextResult,
    BrainFileNotFoundError,
    BrainQueryResult,
    GlobalContextView,
    OpenAreaResult,
    OpenFileResult,
    UnsupportedBrainFileTypeError,
    get_brain_context,
    open_area,
    open_file,
    query_brain,
)
from brain_sync.application.doctor import DoctorResult, Finding, Severity, deregister_missing, doctor, rebuild_db
from brain_sync.application.init import InitResult, init_brain, update_skill
from brain_sync.application.insights import (
    InsightState,
    delete_insight_state,
    load_all_insight_states,
    load_insight_state,
    save_insight_state,
)
from brain_sync.application.local_files import (
    InvalidKnowledgePathError,
    KnowledgeFileNotFoundError,
    KnowledgePathIsDirectoryError,
    LocalFileAddResult,
    LocalFileCollisionError,
    LocalFileNotFoundError,
    LocalFileRemoveResult,
    UnsupportedLocalFileTypeError,
    add_local_file,
    remove_local_file,
)
from brain_sync.application.placement import (
    DocumentTitleRequiredError,
    PlacementCandidateView,
    PlacementSuggestionResult,
    detect_subtree,
    extract_file_excerpt,
    suggest_document_placement,
)
from brain_sync.application.query_index import AreaIndex, invalidate_area_index, load_area_index
from brain_sync.application.reconcile import (
    ReconcileReport,
    TreeReconcileResult,
    reconcile_brain,
    reconcile_knowledge_tree,
)
from brain_sync.application.regen import RegenFailed, classify_folder_change, invalidate_global_context_cache, run_regen
from brain_sync.application.roots import (
    BrainNotFoundError,
    InvalidBrainRootError,
    resolve_active_root,
    resolve_root,
    validate_brain_root,
)
from brain_sync.application.source_state import SourceState, SyncState, load_state, save_state
from brain_sync.application.sources import (
    AddResult,
    InvalidChildDiscoveryRequestError,
    MigrateResult,
    MoveResult,
    ReconcileResult,
    RemoveResult,
    SourceAlreadyExistsError,
    SourceInfo,
    SourceNotFoundError,
    UnsupportedSourceUrlError,
    UpdateResult,
    add_source,
    check_source_exists,
    list_sources,
    migrate_sources,
    move_source,
    reconcile_sources,
    remove_source,
    update_source,
)
from brain_sync.application.status import StatusSummary, UsageSummary, build_status_summary, get_usage_summary

__all__ = [
    "ALLOWED_EXTENSIONS",
    "DEFAULT_FILE_CHARS",
    "MAX_AREAS_LISTED",
    "MAX_CHILDREN",
    "MAX_FILE_CHARS",
    "MAX_SUMMARY_CHARS",
    "TRUNCATION_MARKER",
    "AddResult",
    "AreaChild",
    "AreaIndex",
    "AreaListing",
    "AreaNotFoundError",
    "BrainContextResult",
    "BrainFileNotFoundError",
    "BrainNotFoundError",
    "BrainQueryResult",
    "DoctorResult",
    "DocumentTitleRequiredError",
    "Finding",
    "GlobalContextView",
    "InitResult",
    "InsightState",
    "InvalidBrainRootError",
    "InvalidChildDiscoveryRequestError",
    "InvalidKnowledgePathError",
    "KnowledgeFileNotFoundError",
    "KnowledgePathIsDirectoryError",
    "LocalFileAddResult",
    "LocalFileCollisionError",
    "LocalFileNotFoundError",
    "LocalFileRemoveResult",
    "MigrateResult",
    "MoveResult",
    "OpenAreaResult",
    "OpenFileResult",
    "PlacementCandidateView",
    "PlacementSuggestionResult",
    "ReconcileReport",
    "ReconcileResult",
    "RegenFailed",
    "RemoveResult",
    "Severity",
    "SourceAlreadyExistsError",
    "SourceInfo",
    "SourceNotFoundError",
    "SourceState",
    "StatusSummary",
    "SyncState",
    "TreeReconcileResult",
    "UnsupportedBrainFileTypeError",
    "UnsupportedLocalFileTypeError",
    "UnsupportedSourceUrlError",
    "UpdateResult",
    "UsageSummary",
    "add_local_file",
    "add_source",
    "build_status_summary",
    "check_source_exists",
    "classify_folder_change",
    "delete_insight_state",
    "deregister_missing",
    "detect_subtree",
    "doctor",
    "extract_file_excerpt",
    "get_brain_context",
    "get_usage_summary",
    "init_brain",
    "invalidate_area_index",
    "invalidate_global_context_cache",
    "list_sources",
    "load_all_insight_states",
    "load_area_index",
    "load_insight_state",
    "load_state",
    "migrate_sources",
    "move_source",
    "open_area",
    "open_file",
    "query_brain",
    "rebuild_db",
    "reconcile_brain",
    "reconcile_knowledge_tree",
    "reconcile_sources",
    "remove_local_file",
    "remove_source",
    "resolve_active_root",
    "resolve_root",
    "run_regen",
    "save_insight_state",
    "save_state",
    "suggest_document_placement",
    "update_skill",
    "update_source",
    "validate_brain_root",
]
